### ISSUE TITLE
Sub sampling data

### ISSUE THREAD

**Issue by FLIMinator** [imperial-photonics/FLIMfit#139]
Hi Ian!

Fred & I are wondering whether the data sub sampling option works?

We were using it an it did work for subsampling of 2. It seems to fail when we first try sub sampling other than 2 i.e. 3 or 4. Perhaps variabless are being updated correclty. It can fit always correctly when we select fit single decay but does not work for fitting all of data. No errors are given in the command line.

To test this error is quite straight forward. Load some data with an irf and sub sample it a few times.

Its an option in FLIMfit that is potentially really useful. 

![sub sampling option in flimfit](https://cloud.githubusercontent.com/assets/7783135/7429626/8450ff4e-effc-11e4-8c0c-1ee196e95fce.jpg)

Regards,

Hugh

**Comment by imunro** [comment]
I'll have a look. Could be another symptom of the Anca/genops bug.

**Comment by imunro** [comment]
Tried this and it seemed to work on my mac from Matlab, (in that the no of points went down as the subsampling went up.)  No genops errors were thrown so if  there is a bug in the deployed code on  t6 at least we know it's not that one.

**Comment by seanwarren** [comment]
This works in the front end but as far as i remember not in the back end. It was only ever for some testing I was doing, what do you guys need it for Hugh?

On 1 May 2015 23:17, imunro <notifications@github.com> wrote:

Tried this and it seemed to work on my mac from Matlab, (in that the no of points went down as the subsampling went up.) No genops errors were thrown so if there is a bug in the deployed code on t6 at least we know it's not that one.

**Comment by FLIMinator** [comment]
Hi Sean,

Perhaps this is not a critical issse. Fred collected some data the other
day. We oversampled the data and wanted to sub sample it in FLIMfit to see
how fitted results changed when changing the fit window cropping and/or sub
sampling to in effect simulate using different acquisition strategies.

Regards,

Hugh
