### ISSUE TITLE
Problem distinguishing .tifs from a stack!

### ISSUE THREAD

**Issue by imunro** [imperial-photonics/FLIMfit#141]
If there is a .tif (say background) in the same .dir as a .tiff stack then it will be loaded as part of the .tif stack!! It looks as if this has always been the behaviour so no intention to fix. 

Mainly reported as a warning not to put other .tifs in with stacks!!

**Comment by seanwarren** [comment]
This is the intended behaviour

**Comment by imunro** [comment]
I know! So "Mainly reported as a warning not to put other .tifs in with stacks!!"
