### ISSUE TITLE
Crashing

### ISSUE THREAD

**Issue by sguldbra** [imperial-photonics/FLIMfit#150]
Flimfit is crashing when I load an image and select "Fit Dataset". Tried twice, each time with the same error message. 

![screenshot_flimfiterror1](https://cloud.githubusercontent.com/assets/12895404/8827983/af95ac38-3087-11e5-96a7-f5fbd215d270.jpg)
![screenshot_flimfiterror2](https://cloud.githubusercontent.com/assets/12895404/8827982/af8db2b2-3087-11e5-8fd6-400b270d9d95.jpg)

**Comment by imunro** [comment]
If you could make that window bigger that would really help.

**Comment by sguldbra** [comment]
Thank you munro. Fortunately it crashed again, so here is part of a bigger window...
![screenshot_flimfiterror3](https://cloud.githubusercontent.com/assets/12895404/8829853/d5c34cb8-3090-11e5-846f-abee4fe3b71d.JPG)

**Comment by imunro** [comment]
As we haven't seen this issue on a 4.10 version. Closing. Please report if it  re-occurs.
