### ISSUE TITLE
FLIMfit v4.9.1 crashes

### ISSUE THREAD

**Issue by sguldbra** [imperial-photonics/FLIMfit#152]
Following procedure makes FLIMfit crash: 
Loading FLIM Data, loading IRF Data (Scattered), want to check the IRF shift first. Therefore, I check that the IRF shift is set to zero, I choose  "Fit IRF shift" (Lifetime tab), set background to a fixed value (measured from a background image), set the algorithm to "Variable Projection", set "Scatter" to "Fitted Globally" (Stray tab) and click "Fit Dataseet". I have the new version of FLIMfit (v4.9.1), downloaded today (23/07/15). Have attached a massive amount of error data. Sorry for the stupid way of saving it, couldn't attach a text file. The files that belong together are slighltly overlapping, I have removed some of the empty lines in the code in order to try and save some space. Thanks. 
![screenshot_flimfitbug_1_part1](https://cloud.githubusercontent.com/assets/12895404/8852493/86c13c3e-314d-11e5-96c3-704befe3b52a.JPG)
![screenshot_flimfitbug_1_part2](https://cloud.githubusercontent.com/assets/12895404/8852492/86c0e892-314d-11e5-8187-734243e812ac.JPG)
![screenshot_flimfitbug_1_part3](https://cloud.githubusercontent.com/assets/12895404/8852494/86c34b32-314d-11e5-98b6-a780335a3130.JPG)
![screenshot_flimfitbug_1_part4](https://cloud.githubusercontent.com/assets/12895404/8852496/86c5cf56-314d-11e5-8333-eca43667489a.JPG)
![screenshot_flimfitbug_1_part5](https://cloud.githubusercontent.com/assets/12895404/8852495/86c50a80-314d-11e5-8257-b557eddf114e.JPG)
![screenshot_flimfitbug_1_part6](https://cloud.githubusercontent.com/assets/12895404/8852497/86ca319a-314d-11e5-90f1-c69ddffae04f.JPG)
![screenshot_flimfitbug_2_part1](https://cloud.githubusercontent.com/assets/12895404/8852499/86d64a98-314d-11e5-9a49-40344c24d80f.JPG)
![screenshot_flimfitbug_2_part2](https://cloud.githubusercontent.com/assets/12895404/8852500/86d8322c-314d-11e5-8a68-b22c91c71e0d.JPG)
![screenshot_flimfitbug_3_part1](https://cloud.githubusercontent.com/assets/12895404/8852498/86d4d230-314d-11e5-8e62-419e77ff0303.JPG)
![screenshot_flimfitbug_3_part2](https://cloud.githubusercontent.com/assets/12895404/8852501/86ef6d34-314d-11e5-82bd-53b4ca9c3664.JPG)

**Comment by imunro** [comment]
It's unclear whether this is still an issue on the new build system so closing! @sguldbra if you see this with 4.10- something please re-open.
