### ISSUE TITLE
crash in "init_memory_mapping" when trying to load large OPT-FLIM OME.tiff file

### ISSUE THREAD

**Issue by yalexand** [imperial-photonics/FLIMfit#156]
Size of data was about 15G.
Computer's was Win 7 Enterprise 64, with installed memory 48G.
We keep trying but for now didn't succeed to load it. 

![flimfit error when loading very large opt-flim ometiff](https://cloud.githubusercontent.com/assets/1183151/9333423/c09dc34a-45c1-11e5-8580-9d43fc431493.PNG)

**Comment by imunro** [comment]
I suspect this is just unmanageably large data and no longer an issue .
