### ISSUE TITLE
Fail on opening multi-channel single pixel .sdt file.

### ISSUE THREAD

**Issue by imunro** [imperial-photonics/FLIMfit#179]
Berlin report (by private e-mail) a problem with opening a single-pixel .sdt file  as polarised data with 4.10.1.

Preliminary investigation shows that attempting to open any channel > 1  gives an error.

running bio-formats (v5.1.7) showinf  tool gives the errors below:
Strongly suggesting that the problem lies either in the file or in the bioformats sdt reader.

  ./showinf rh6g_469nm_3au.sdt
Checking file format [SPCImage Data]
Initializing reader
SDTReader initializing rh6g_469nm_3au.sdt
Reading header
Populating metadata
Initialization took 0.04s

Reading core metadata
filename = rh6g_469nm_3au.sdt
Series count = 1
Series #0 :
	Image count = 1024
	RGB = false (1)
	Interleaved = true
	Indexed = false (true color)
	Width = 1
	Height = 1
	SizeZ = 1
	SizeT = 256 (1 Spectra x 256 Lifetime)
	SizeC = 4
	Thumbnail size = 1 x 1
	Endianness = intel (little)
	Dimension order = XYZTC (certain)
	Pixel type = uint16
	Valid bits per pixel = 16
	Metadata complete = true
	Thumbnail series = false
	-----
	Plane #0 <=> Z 0, C 0, T 0
	Plane #510 <=> Z 0, C 1, T 254
	Plane #511 <=> Z 0, C 1, T 255
	Plane #512 <=> Z 0, C 2, T 0
	Plane #513 <=> Z 0, C 2, T 1
	Plane #514 <=> Z 0, C 2, T 2
	Plane #1023 <=> Z 0, C 3, T 255

Reading pixel data (0-1023)
Exception in thread "main" java.lang.IllegalArgumentException
	at java.nio.Buffer.position(Buffer.java:244)
	at loci.common.NIOFileHandle.buffer(NIOFileHandle.java:603)
	at loci.common.NIOFileHandle.skipBytes(NIOFileHandle.java:449)
	at loci.common.RandomAccessInputStream.skipBytes(RandomAccessInputStream.java:590)
	at loci.formats.in.SDTReader.openBytes(SDTReader.java:185)
	at loci.formats.FormatReader.openBytes(FormatReader.java:920)
	at loci.formats.ImageReader.openBytes(ImageReader.java:437)
	at loci.formats.ReaderWrapper.openBytes(ReaderWrapper.java:335)
	at loci.formats.gui.BufferedImageReader.openImage(BufferedImageReader.java:86)
	at loci.formats.tools.ImageInfo.readPixels(ImageInfo.java:804)
	at loci.formats.tools.ImageInfo.testRead(ImageInfo.java:1042)
	at loci.formats.tools.ImageInfo.main(ImageInfo.java:1117)

**Comment by imunro** [comment]
Addressed by https://github.com/openmicroscopy/bioformats/pull/2253
Just need to get these changes into a FLIMfit release now.

**Comment by imunro** [comment]
Whether we can get this into 4.10.4 depends on the bio-formats release schedule.

**Comment by seanwarren** [comment]
@imunro - do you want to wait for this or should we release without?

**Comment by imunro** [comment]
Hi Sean

I’m tempted to try and release rather than wait and then do a 4.10.5 when this comes out  but  I’ve left myself a lot to do
this week. (Big stack of marking!) so may not have time befiore I go.

Let’s see how much I can get done tomorrow then decide ?

Ian


On 20 Mar 2016, at 22:26, Sean Warren <notifications@github.com<mailto:notifications@github.com>> wrote:


@imunro<https://github.com/imunro> - do you want to wait for this or should we release without?

**Comment by seanwarren** [comment]
No problem, this isn't a massive blocker from my point of view - people can always export as ASCII files

**Comment by imunro** [comment]
Ah! Maybe my Portugese contact doesn’t know that.
I’ll forward the e-mail thread.

Ian


On 20 Mar 2016, at 23:10, Sean Warren <notifications@github.com<mailto:notifications@github.com>> wrote:


No problem, this isn't a massive blocker from my point of view - people can always export as ASCII files

**Comment by imunro** [comment]
bio-formats 5.1.9 is planned for release on the 11th.@seanwarren I  suggest 2 or 3 days later for 4.10.4.
If you're happy with that I suggest no more "enhancements" in the master thread from now  just bug fixes.
Sound alright ?

**Comment by seanwarren** [comment]
sounds good to me

**Comment by imunro** [comment]
Bio-formats 5.1.9 now scheduled for Tue 19th!

**Comment by imunro** [comment]
@seanwaren 5.1.9 is finally out (catching me completely by surprise). I'm not 100% sure how to generate an RC though? Change tags and run Release builds or is it more complex?

**Comment by seanwarren** [comment]
Great, no need to do a release build - it's just a tag. Lets test a bit and then do the release

**Comment by imunro** [comment]
That was my plan for tomorrow. Don't the latest builds have the git-commit tag in the name though ?

**Comment by seanwarren** [comment]
Only if there have been changes since the last tag - the commit you tag with 4.11.0RC won't have anything appended

**Comment by imunro** [comment]
Ooops! Looks like you might already have done this - times foxed me - I haven't woken up yet

**Comment by imunro** [comment]
Looks ok. As far as I can see you built (I guess for testing)  but didn't tag & then I tagged. Find any problems?
