### ISSUE TITLE
save data settings

### ISSUE THREAD

**Issue by Fredxxx** [imperial-photonics/FLIMfit#181]
minor issue: it would be quite handy if the fit properties would also be included in the save data settings. Like (Lifetime, stray, anisotrop, FRET, advanced)

**Comment by Fredxxx** [comment]
Hey Sean,

cannot really find a save or load fit settings button. But if this is already included I will ask Ian to show me where it exactly is.

Thanks
Frederik

**Comment by imunro** [comment]
@Fredxxx I think, by a process of elimination, that  it must be "Export Initial Fit Parameters"
