### ISSUE TITLE
Support for PicoQuant .bin files is broken starting from version 4.10

### ISSUE THREAD

**Issue by ilyaradko** [imperial-photonics/FLIMfit#182]
It used to work without problem, at least in the previous version 4.9, but after updating to version 4.10.3, .bin files are either cannot be loaded at all, or loaded as broken ones.

**Comment by imunro** [comment]
Many thanks for spotting that I'll investigate and get back to you.

**Comment by imunro** [comment]
@seanwarren This looks like an easy fix - simply switch back to using bio-formats for these files, or is there extra functionality in the new  reader that you have added?
in fact I'm planning to address https://github.com/imperial-photonics/FLIMfit/issues/163 in the next day or so so both could be tackled together.

**Comment by seanwarren** [comment]
@ilyaradko - thanks for the report. Would you be able to share some a test image with us so we can get to the bottom of this? If you could email it to s.warren@garvan.org.au that would be great. 

@imunro - I was having problems loading bin files with the BF reader but lets try rolling back and I'll see if I can still read them

**Comment by ilyaradko** [comment]
Sean, I just sent you two small test files to your email - an IRF profile and a 10x10 pixels image.

**Comment by imunro** [comment]
Sean - if there are problems with your files and the Bf reader I'd really like to get them fixed as this is much more widely useful than just in FLIMfit ( Imagej, Icy, Matlab, OMERO etc) so can you also send me the files in question.

**Comment by imunro** [comment]
Thinking about it Sean - even better would be to upload directly to https://www.openmicroscopy.org/qa2/qa/upload/   with some feed back describing the issues. If we can get on this quick we can get any problems fixed in the upcoming bio-formats release.

**Comment by imunro** [comment]
@seanwarren I fear we may have missed the boat for bio-formats 5.1.8

**Comment by imunro** [comment]
@ilyaradko @seanwarren  There is now a beta-test version of FLIMfit including my proposed solution to this Issue available from:
http://ci.flimfit.org/job/flimfit-merge-mac/gcsObjects/  
or 
http://ci.flimfit.org/job/flimfit-merge-win/gcsObjects/
Would it be possible for you to check this version works with your .bin files.

NB there is a known issue that files larger than a threshold (currently 900 timepoints of 200 x 200 pixels) will load extremely slowly. If your files are larger than this then please upload a sample to https://www.openmicroscopy.org/qa2/qa/upload/   and we can get the threshold increased accordingly.

**Comment by ilyaradko** [comment]
@imunro Sorry for the delay - could not test it until now. Unfortunately, nothing has changed for me - the behaviour is exactly the same: .bin files can either not be loaded at all, or they are cut in dimension by half (and also transposed compared to version 4.9 - but this is not a problem).

**Comment by imunro** [comment]
Many thanks. That's unexpected. Could I ask you to upload a test file/s to https://www.openmicroscopy.org/qa2/qa/upload/ please.

**Comment by seanwarren** [comment]
@imunro, this should now be fixed as of 0d5d06.  I will test again tomorrow morning and send a version to test. Cheers

**Comment by imunro** [comment]
Hi Sean. Overriding the existing bio-formats reader (unless there's a reason for it )  gives me a problem as we now have (potentially) divergent behaviour when loading from file or OMERO.

**Comment by ilyaradko** [comment]
@imunro A little update. I just figured out that large files are opened much faster due to some optimization, which reads only every second row and every second column in the data file (hence, the reduced resolution by one half). The .dat file, which I cannot open is an IRF function, which is just a 1x1 pixel data (one histogram). My guess is that the IRF cannot be loaded because of this speed optimization, which ignores the first pixel and tries to read the second non-existing one.
I have uploaded the IRF following your link - the file name is IRF_256.bin

**Comment by imunro** [comment]
Thanks @ilyaradko

**Comment by seanwarren** [comment]
Fixed as of 6d3a79826753589f5c8e3e2d79dc0b0e0c86fdb3. Will be released in v4.10.4

**Comment by imunro** [comment]
Finally released as v4.11.0 see http://lists.openmicroscopy.org.uk/pipermail/flimfit-users/2016-April/000036.html
