### ISSUE TITLE
SV IRF export/import

### ISSUE THREAD

**Issue by seanwarren** [imperial-photonics/FLIMfit#184]
Need to make sure IRF settings are reset before loading SV IRF xml file

**Comment by seanwarren** [comment]
Hopefully fixed in 64dd246f11bc7822b49655fa99d7eadf27a50490. 
@WenjunGuo2015 @Fredxxx - please could you test that this fixes your SV IRF loading issue that we discussed over christmas using the version linked below?

http://ci.flimfit.org/job/flimfit-latest-win/62/gcsObjects/

**Comment by WenjunGuo2015** [comment]
Hey Sean, I have just tested the new version by first loading a .xml file as the IRF, changing the IRF settings, and then loading another .xml file as the IRF. Unfortunately the IRF settings, e.g. background and t0, were not reset to zero. Do you think I was looking at the right things?

**Comment by seanwarren** [comment]
Actually the fix will only apply to new xml files - could you try creating a new one and loading that please?

On 19 Mar 2016 9:43 am, WenjunGuo2015 <notifications@github.com> wrote:

Hey Sean, I have just tested the new version by first loading a .xml file as the IRF, changing the IRF settings, and then loading another .xml file as the IRF. Unfortunately the IRF settings, e.g. background and t0, were not reset to zero. Do you think I was looking at the right things?

—
You are receiving this because you were assigned.
Reply to this email directly or view it on GitHub<https://github.com/imperial-photonics/FLIMfit/issues/184#issuecomment-198569813>

NOTICE
Please consider the environment before printing this email. This message and any attachments are intended for the addressee named and may contain legally privileged/confidential/copyright information. If you are not the intended recipient, you should not read, use, disclose, copy or distribute this communication. If you have received this message in error please notify us at once by return email and then delete both messages. We accept no liability for the distribution of viruses or similar in electronic communications. This notice should not be removed.

**Comment by WenjunGuo2015** [comment]
Hi Sean, the new version works perfectly with newly-generated .xml files. Thank you very much for the fix.

**Comment by imunro** [comment]
Thanks Wenjun.
