### ISSUE TITLE
Mac-merge build isn't updating OMEROMatlab/libs

### ISSUE THREAD

**Issue by imunro** [imperial-photonics/FLIMfit#188]
Currently the artifacts from mac-merge build is broken giving the following:

Error using front_end_menu_controller/menu_OMERO_Load_FLIM_Data_callback (line 383)
Java exception occurred: 
java.lang.NoClassDefFoundError: omero/gateway/model/PlateData

So far I have determined that OMEUiUtils.jar is correct (by running locally from source using the version copied from the MCR cache)
and that the classpath is correct (thanks for the suggestion @sbesson)

Looking at /.mcrCache9.0/FLIMfi0/OMEROMatlab/libs however it looks as if we have an old omero_client.jar modified on 24 Sep 2015.

Now need to determine why this build isn't picking up the correct version.

The console logs contain:

mv: rename OMERO.matlab-5.2.2-ice35-b17/annotations to FLIMfitFrontEnd/OMEROMatlab/annotations: Directory not empty
mv: rename OMERO.matlab-5.2.2-ice35-b17/delete to FLIMfitFrontEnd/OMEROMatlab/delete: Directory not empty
mv: rename OMERO.matlab-5.2.2-ice35-b17/helper to FLIMfitFrontEnd/OMEROMatlab/helper: Directory not empty
mv: rename OMERO.matlab-5.2.2-ice35-b17/image to FLIMfitFrontEnd/OMEROMatlab/image: Directory not empty
mv: rename OMERO.matlab-5.2.2-ice35-b17/io to FLIMfitFrontEnd/OMEROMatlab/io: Directory not empty
mv: rename OMERO.matlab-5.2.2-ice35-b17/libs to FLIMfitFrontEnd/OMEROMatlab/libs: Directory not empty
mv: rename OMERO.matlab-5.2.2-ice35-b17/roi to FLIMfitFrontEnd/OMEROMatlab/roi: Directory not empty

**Comment by sbesson** [comment]
Looking at the content of `OMEROMatlab` on CI e.g. `OMEROMatlab/roi/createRectangle.m` is still at version 5.1.x (using `RectI`) although OMERO.matlab 5.2.x is downloaded. In order to solve this issue:
- eithe the Git workspace should be cleaned via the Jenkins configuration (preferred)
- or the `mv` command should be updated to remove dangling folders before renaming

**Comment by imunro** [comment]
I was just trying  the second option when you commented - so have now added "clean after checkout" to the Source Code Management step instead.

**Comment by imunro** [comment]
Having moved back to my flat for working internet  in oeder to be able to download it - that seems to have worked. @swarren Are you happy for me to implement that across all the builds?

**Comment by swarren** [comment]
I think you mentioned the wrong person. I know nothing about this repo/project.

**Comment by imunro** [comment]
My apologies.

**Comment by imunro** [comment]
That seemed to work. @seanwarren are you happy for me to replicate that change across the other builds?

**Comment by seanwarren** [comment]
Yup cheers Ian
