### ISSUE TITLE
gh-pages website issues

### ISSUE THREAD

**Issue by hflynn** [imperial-photonics/FLIMfit#201]
http://imperial-photonics.github.io/FLIMfit/news/ doesn't include the release announcement for 4.10.3 (http://lists.openmicroscopy.org.uk/pipermail/ome-users/2016-February/005863.html)

Also, once you have navigated to the docs, you can't go back to main home page without using the back button, your FLIMfit home icon in the top left corner only goes back to docs front page which you can always navigate to using the side menu anyway.

**Comment by seanwarren** [comment]
@hflynn thanks for the comments - I've updated the news page now. 
The docs are a bit more complex as I'd need to edit the sphinx theme, I'll have a look into it

**Comment by hflynn** [comment]
Thanks @seanwarren 

I seem to remember having a similar issue with our blog, I'll take a look later if I get chance and let you know if I have any ideas for you to try.

**Comment by hflynn** [comment]
Ah yes, having had a poke around, I see what you mean. Might be easiest to just add a hardcoded link in your menu. Just a suggestion anyway, I leave it to you if it's more bother than it's worth. Feel free to close this if you like.

**Comment by seanwarren** [comment]
@hflynn I've fixed this by manually editing the theme to point to flimfit.org, I'll see if there is a more elegant way in the future but for now it does the job!

**Comment by hflynn** [comment]
:+1: Thanks very much, works for me!
