### ISSUE TITLE
Picoquant .bin files broken again.

### ISSUE THREAD

**Issue by imunro** [imperial-photonics/FLIMfit#209]
On attempting to open a .bin file I see a "loading options" prompt. Using the defaukt settings the image fails to load.

This looks like functionality for selecting a size when  binning FIFO data but AFAIK the .bin files are already binned (hence the name) so the size is known.

**Comment by imunro** [comment]
I also see: 
2016-04-07 22:01:00.640 FLIMfit[7061:41857] Couldn't find or read strings file SlicesStrings
in the text window but haven't definitely established this is related.

**Comment by seanwarren** [comment]
Thanks for picking this up @imunro - this is actually not related to the spatial binning which is implemented for bin files. I changed the way the number of channels was stored and missed this reader. Should be fixed in 0635f0f787ef81a69f7b92367ca834ba382c7731

**Comment by imunro** [comment]
Looks good now - 12 hr overnight bug fixing service. Hah!
