### ISSUE TITLE
Consider adding a z-T viewer tab.

### ISSUE THREAD

**Issue by imunro** [imperial-photonics/FLIMfit#211]
Following discussion with Berlin on restricting loading from multi-D  data to either a z-stack or a Time-series "because FLImfit can't do  2D display" it occurs to me that the Plate tab does exactly that.

@seanwarren How hard do you think it would be to add a tab (based on plate) that displayed z-T as a grid rather than Row-Column ? and is it worth considering?

**Comment by seanwarren** [comment]
@imunro - this would probably be relatively straightforward, although it might have to be modelled on the gallery tab with a scroll. An alternative approach might be to have an imagej style window where you can scroll through the dimensions movie-style

**Comment by imunro** [comment]
Hmm perhaps 'Gallery" might be a better starting point - thanks.

**Comment by imunro** [comment]
On preliminary investigation the first step is probably to implement this for a dataset where there is  one non single dimension across multiple files. e.g a z-stack in each file and one file per time-point.
Step 1: allow selection of multiple planes for . 1 file. - maximae set in get_zct
Step 2: Set obj.names in load_multiple.
Step 3. Ensure all planes load correctly.

Finally it's then worth working on display - probably can't be done before re-assignment to non-OME work with release of 4.11.

**Comment by imunro** [comment]
What we have so far (as of above PR) allows the Z or T to be overlaid as text in the Gallery tab so I feel that will do the job.
