### ISSUE TITLE
Loading tif stack broken

### ISSUE THREAD

**Issue by seanwarren** [imperial-photonics/FLIMfit#212]
Somewhere along the way with OMERO merges the ability to load tif stacks has become badly broken 

- Tries to look for non existent path
- Loading tries to find first file containing delay - this is wrong for the general case (e.g. 5500 contains 500).

**Comment by imunro** [comment]
Well-spotted I'll look at that today.

**Comment by seanwarren** [comment]
I'm sorting it now

**Comment by imunro** [comment]
ah already have it

**Comment by imunro** [comment]
both do a pr ?

**Comment by seanwarren** [comment]
Sorry I got a bit carried away and have committed straight to master

**Comment by seanwarren** [comment]
should be fixed in d018c304cb0f04433288924b14e5bdc5aae6c755

**Comment by imunro** [comment]
Do you still use this format then? I still test (hopefully would have caught this in pre-release testing) but didn't think it was still used.

**Comment by seanwarren** [comment]
I got an email from Lambert, they have been giving it a go. It's a useful format for simulated data etc

**Comment by imunro** [comment]
Is it ok with you if I put the waitbar back? OCD!
