### ISSUE TITLE
4.10.3 Installs on Windows as 4.10.3GCxxxx

### ISSUE THREAD

**Issue by imunro** [imperial-photonics/FLIMfit#214]
This may have been a glitch on the OME release or on ci.flimfit  but it does mean that the Release looks like a beta-version which is confusing.

**Comment by seanwarren** [comment]
where are you seeing this string ian? cheers

**Comment by imunro** [comment]
The desktop shortcut seems to be called that. As I said above it's possible that the wrong file was copied to the OME downloads page so may not be at your end.

**Comment by imunro** [comment]
Not of any relevance as   4.11 looks ok .
