### ISSUE TITLE
dll's and less crucially .dylibs should be downloadable.

### ISSUE THREAD

**Issue by imunro** [imperial-photonics/FLIMfit#215]
See http://lists.openmicroscopy.org.uk/pipermail/flimfit-users/2016-April/000033.html

**Comment by seanwarren** [comment]
Fixed for latest build, just need to add to merge/release

**Comment by imunro** [comment]
Cool thanks.

**Comment by seanwarren** [comment]
Done for release as well - no changes to the build itself so you're good testing the current build

**Comment by imunro** [comment]
I've been testing the output from latest - with a view to just copying that to the Download pages.
Do I need to use the Release builds at all ?

**Comment by seanwarren** [comment]
I think it's better to use the release build if poss...

**Comment by imunro** [comment]
ok I'll re-check

**Comment by imunro** [comment]
Is it ok to run the release builds then ?

Ian


On 19 Apr 2016, at 11:18, Sean Warren <notifications@github.com<mailto:notifications@github.com>> wrote:


I think it's better to use the release build if poss...
