### ISSUE TITLE
Unexpected error message

### ISSUE THREAD

**Issue by imunro** [imperial-photonics/FLIMfit#216]
Found during pre-release testing of 4.11.0 on terminalsix - Windows server
Opening a Picoquant .bin file gives the error below. NB in the test window not via the new error reporting.
The file does , however, appear to load correctly

<img width="706" alt="screen shot 2016-04-19 at 15 47 00" src="https://cloud.githubusercontent.com/assets/1183110/14643418/3c6e08e6-0646-11e6-86fc-d395c6a510f4.png">

**Comment by imunro** [comment]
My assumption is that this is arising when I use bio-formats to check the file type before handing it over to FLIMReader. @seanwarren can we live with this for this release?

**Comment by seanwarren** [comment]
@imunro, are we using bioformats or FLIMreader for .bin data at the moment? Have we resolved the loading time issues with bin files now?

**Comment by imunro** [comment]
We are, as of 4.11 using FLIMReader, Bio-Formats is used to check all file-types first though.
I think I've improved the loading time situation ( it will still be slower than the FLIMReader equivalent for larger files though) but this won't be available until Bio-Formats 5.2.0.

**Comment by seanwarren** [comment]
OK cool. I'm happy with to leave this as-is then.
