### ISSUE TITLE
4.11RC still prompts me to upgrade to 4.10.3 ?

### ISSUE THREAD

**Issue by imunro** [imperial-photonics/FLIMfit#217]
At least on windows so far.

**Comment by seanwarren** [comment]
Whoops - turns out I can't compare three numbers. Should be fixed as of 8b8282d081a79f79a29d71290b25de38eeeb780b

**Comment by imunro** [comment]
I ought to do a full re-test but as I'm no longer officially working on FLIMfit we may have to go for the "fingers crossed" approach.

**Comment by seanwarren** [comment]
It's only a new line, I'm sure it'll be fine...

**Comment by imunro** [comment]
Moved the tags and started the release build.

**Comment by imunro** [comment]
I fear mac-garvan may have fallen over again.
