### ISSUE TITLE
"Sorry the files could not be downloaded" when installing on Windows.

### ISSUE THREAD

**Issue by imunro** [imperial-photonics/FLIMfit#221]
I am now getting this incredibly unhelpful error message when trying to install 4.11.0 on a variety of Windows machines.  It seems to apply both to the files from http://downloads.openmicroscopy.org/flimfit/4.11.0/  and  those from http://ci.flimfit.org/job/flimfit-release-win/gcsObjects/. This is baffling enough as these files were tested before release but on at leas one machine (Server R2012) I get the same with the 4.10.3 release. It looks as if this might happen when the MCR download starts - but it happens even when the correct MCR is already installed.

**Comment by seanwarren** [comment]
@imunro - looks like the ghostscript server structure has changed! I'm moving the ghostscript download to GatherDependencies.bat and bundling it into the installer

**Comment by imunro** [comment]
Well-spotted! I couldn't work out what was going on. Microsoft being amazingly helpful here.
Guess we better get 4.11.1 out fairly quickly. 
Shall I  send out a heads-up on FLIMfit & OME users ?

**Comment by seanwarren** [comment]
I think I've almost got a fix working so let's wait til Monday and hopefully we can send an email with a new version

**Comment by imunro** [comment]
OK FYI Monday is a bank holiday here so my time may be a bit limited.

**Comment by seanwarren** [comment]
OK this should be fixed in 0d0871b7f3bb53abdee0147f5ac6820d9cd9d85d . I've tested locally and it seems to work well. Could you test as well please @imunro (build 88 on flimfit-latest-win) when you have time?

**Comment by imunro** [comment]
Successfully installed on Win Server R2012 & passed a very quick fire-test.
Only issue was the following but IIRC this is an old issue & not relevant.

<img width="753" alt="screen shot 2016-05-02 at 11 03 16" src="https://cloud.githubusercontent.com/assets/1183110/14952142/d9434762-1055-11e6-94ce-ce0a3fe2b241.png">

**Comment by imunro** [comment]
So what's the plan @seanwarren. Release via your new downloads page or as before?
