### ISSUE TITLE
cannot seem to segment more than 256 (8bit) cells when loading mask with more than this number.

### ISSUE THREAD

**Issue by FLIMinator** [imperial-photonics/FLIMfit#223]
Cannot segment more than 255 objects

**Comment by seanwarren** [comment]
This is a design limitation ; the masks are stored as 8bit ints. How critical is this?

**Comment by FLIMinator** [comment]
Hey Sean, I have a data set that involves segmenting nuclei and the count often exceeds 256 - more like 500 per image. I'd like to extract cell-wise lifetimes to get intercellular distributions and the plan is to use them in a paper I'm in the process of writing. If its possible to bump the number up to 16bit ints in the near future it would be massively appreciated. I can forsee this limitation becoming a recurring issue with montaged FLIM images/images greater than 256x256/tumors with densly packed cells.

I'm aware this is on your time so feel free to tell me to wait! I was thinking as a quick fix I could convert my sdt data into quadrants and make x4 tiff stacks.

**Comment by seanwarren** [comment]
Cool I'll have a look into it
(who is this by the way?)

**Comment by seanwarren** [comment]
OK was simpler than expected. Could you test the version below for me please?
It would be good if you could check that segmentation file loading/saving also works as expected. 
If you're loading segmentation files from an external source, make sure they are saved as 16bit or higher tifs! 

windows: https://storage.googleapis.com/flimfit-downloads/merge/4.11.1-3-g07c8a94/FLIMfit%204.11.1-3-g07c8a94%20Setup%20x64.exe

mac: https://storage.googleapis.com/flimfit-downloads/latest/4.11.1-3-g07c8a94/FLIMfit_4.11.1-3-g07c8a94_MACI64.zip

**Comment by FLIMinator** [comment]
Thanks for this Sean,

Sorry late getting back to you, graduated yesterday and went to the
pub......

The mask works but when I fit it only fits what appears to be ~ 256
segments. I saved the image as uint16.

Please try the data, using the settings file within, I have provided if you
have time. I pulled an old FLIM image from PhD because the data for the
paper is over at Crick ( still visit to analyse data there) and I'm back at
Imperial. There are exactly 500 labels in this image. See the screenshots
I've put in the folder also, they show the segmentation window found 500
regions.

Cheers,

Hugh

**Comment by seanwarren** [comment]
Hi Hugh, no worries. I think I see the problem. Could you send the data to s.warren@garvan.org.au please? Attaching files to github doesn't seem to work by email. I'm thinking to set the limit to 4096 as there are some minor performance implications, does this seem reasonable to you?

**Comment by seanwarren** [comment]
Hi Hugh, I haven't had time to test the changes but I think this one should work: https://storage.googleapis.com/flimfit-downloads/merge/4.11.1-4-g5aba48f/FLIMfit%204.11.1-4-g5aba48f%20Setup%20x64.exe . Let me know how you get on

**Comment by FLIMinator** [comment]
Thanks Sean!

That works - I can generate results tables with 500 regions.

Thanks so much for the help/your time. Talk soon.

Cheers,

Hugh

**Comment by seanwarren** [comment]
Great, good luck with the paper. Catch you soon

**Comment by seanwarren** [comment]
This will be released with 4.11.2

**Comment by FLIMinator** [comment]
Thanks again Sean, see you soon hopefully.
