### ISSUE TITLE
Load FLIM dataset error, crashes halfway through loading using 4.11.1

### ISSUE THREAD

**Issue by natandrews** [imperial-photonics/FLIMfit#232]
Subscripted assignment dimension mismatch.

Error in flim_data_series/load_flim_cube (line 330)

Error in flim_data_series/load_selected_files (line 91)

Error in flim_data_series/load_multiple (line 126)

Error in flim_data_series/load_data_series (line 150)

Error in flim_data_series_controller/load_data_series (line 105)

Error in front_end_menu_controller/menu_file_load_widefield_callback (line 661)

Error in front_end_menu_controller>@(varargin)obj.menu_file_load_widefield_callback(varargin{:})

Error in escaped_callback (line 7)

Error in front_end_menu_controller>@(x,y)escaped_callback(x,y,fcn) (line 257)

**Comment by imunro** [comment]
Hi is it possible one image is a different size in any dimension? There should be checks but maybe something slipped through. If not can you point me at the data please?

**Comment by natandrews** [comment]
It could be possible… It does always stop in the same place but other than going through all the folders manually I’m not sure how to find out? The data is here:
/Volumes/fogim_datastore/User data/Natalie Andrews/May/renamed data for flimfit

**Comment by imunro** [comment]
Thanks I'll try and have a look tomorrow.

**Comment by imunro** [comment]
Hi Natalie  I'm trying to load subsets of your data to see if I can pin down the problem.
I had no problems loading Fish2 but after loading I did get the following:

Error using circshift
Invalid shift type: must be a real finite integer vector.

I don't suppose you have any idea what might be causing that?

Error in flim_data_series/compute_tr_data (line 92)
        t_inc_perp = circshift(t_inc,[1 -coarse_shift]);


Error in flim_data_series/init_dataset (line 127)
    obj.compute_tr_data();

**Comment by imunro** [comment]
It turns out that the above error is generated when you load any of your data -( I can get it loading a single image via File-> Load Data) and that it's because there are no delays associated (they are all NaNs). This suggests that your file names do not adhere to the convention for tiff-stack data. I suggest renaming so that the names match a known-working data set.
e.g INT_002300 T_01000.tif

**Comment by imunro** [comment]
I've had a quick look and it looks as if the "T_"bit  might be critical and that the last 6 chars should contain the delay.

**Comment by imunro** [comment]
I've added some code to make it fail a bit more elegantly when it can't recognise filenames. Commit cb4ba5a

**Comment by natandrews** [comment]
Sorry I missed all of this, I was imaging all day! I’ll try this but if it applies to all of my data will it still have problems?

**Comment by imunro** [comment]
Hi Nat

The extra bit of code that I added won't kick in until the next release so 4.11.1 will still crash I'm afraid.
I'm afraid that I didn't quite follow "if it applies to all of my data will it still have problems?"?
