### ISSUE TITLE
Error on loading SV IRF

### ISSUE THREAD

**Issue by Powerfultool** [imperial-photonics/FLIMfit#239]
Error using vertcat
Dimensions of matrices being concatenated are not consistent.

Error in flim_data_series/compute_tr_irf (line 226)

Error in flim_data_series/set.t_irf_min (line 687)

Error in flim_data_series/load_irf (line 111)

Error in front_end_menu_controller/menu_irf_image_load_callback (line 971)

Error in front_end_menu_controller>@(varargin)obj.menu_irf_image_load_callback(varargin{:})

Error in escaped_callback (line 7)

Error in front_end_menu_controller>@(x,y)escaped_callback(x,y,fcn) (line 257)

**Comment by seanwarren** [comment]
Could we have a bit more information about when this occurred? Can you send me the problematic data please

**Comment by imunro** [comment]
Appears to be the same error addressed in #266 so should be fixed in v4.12.1
