### ISSUE TITLE
Compute_tr_data called twice in init dataset

### ISSUE THREAD

**Issue by imunro** [imperial-photonics/FLIMfit#248]
Found during debugging of #236. As in #246 setting type_background and then (expilicitly) compute_tr_data means that  the latter is called twice causing a long delay with v.large files.

**Comment by imunro** [comment]
@seanwarren When you get some time I'd really appreciate a sanity check on this one - it's a critical part of the code and one  I've stayed away from changing in the past.

**Comment by imunro** [comment]
Actuallt @seanwarren scratch that for now! It looks as if it's more complicated than I realised. Leave it with me for a bit.

**Comment by seanwarren** [comment]
@imunro - compute_tr_data shouldn't be called twice in the initialisation; no transformation happens until the the `init` flag is set at the end of the initialisation.

**Comment by imunro** [comment]
The issue seems to be that a lot of variables have change listeners each of which call compute_tr_data.
So as init_dataset sets the variables it gets called many times. I'll check on that flag.

**Comment by imunro** [comment]
Thanks for the hint  I get it now. It gets called a lot but just returns until the init flag is set. 
Closing this accordingly.
