### ISSUE TITLE
Errors on loading FLIM data

### ISSUE THREAD

**Issue by ilyaradko** [imperial-photonics/FLIMfit#254]
I have version 4.9.1, which used to work fine. I have not been using it for several months, and now when I try to load FLIM data (which I successfully did before), FLIMfit gives the following errors in the console:

> Attempted to access sizeZCT(3); index out of bounds because numel(sizeZCT)=2.
> Error in flim_data_series/get_ZCT (line 43)
> Error in flim_data_series/load_multiple (line 54)
> Error in flim_data_series/load_single (line 77)
> Error in flim_data_series_controller/load_single (line 159)
> Error in front_end_menu_controller/menu_file_load_single_callback (line 583)
> Error in front_end_menu_controller/set_callbacks/@(varargin)obj.menu_file_load_single_callback(varargin{:})
> Error using waitfor
> Error while evaluating Menu Callback

What could have changed in my system that broke functionality of FLIMfit and is there a way to troubleshoot? I tried reinstalling both FLIMfit and Matlab compiler runtime without success.

**Comment by seanwarren** [comment]
Hi @ilyaradko, could you please let me know which version you're using? 
I've just tested the previous data you send to me in the latest version and it seems to load ok.

Thanks

**Comment by ilyaradko** [comment]
Hi @seanwarren. The described issue is with version 4.9.1.
I have also tried versions 4.11.0 and 4.11.1 - they do load data files, but show some nonsense. In case of  4.11.0 and 4.11.1, the console gives the following output:

> Aug 08, 2016 11:52:52 AM org.scijava.nativelib.BaseJniExtractor extractJni
> INFO: Couldn't find resource META-INF/lib/windows_64/ SlideBook6Reader.dll
> Aug 08, 2016 11:52:52 AM org.scijava.nativelib.NativeLibraryUtil loadNativeLibrary
> WARNING: IOException creating DefaultJniExtractor
> java.io.IOException: Couldn't find resource META-INF/lib/windows_64/ SlideBook6Reader.dll
>         at org.scijava.nativelib.BaseJniExtractor.extractJni(BaseJniExtractor.java:144)
>         at org.scijava.nativelib.NativeLibraryUtil.loadNativeLibrary(NativeLibraryUtil.java:265)
>         at loci.formats.in.SlideBook6Reader.<clinit>(SlideBook6Reader.java:93)
>         at java.lang.Class.forName0(Native Method)
>         at java.lang.Class.forName(Unknown Source)
>         at loci.formats.ClassList.<init>(ClassList.java:127)
>         at loci.formats.ClassList.<init>(ClassList.java:85)
>         at loci.formats.ImageReader.getDefaultReaderClasses(ImageReader.java:78)
> 
>         at loci.formats.ImageReader.<init>(ImageReader.java:115)
>         at loci.formats.ReaderWrapper.<init>(ReaderWrapper.java:62)
>         at loci.formats.ChannelFiller.<init>(ChannelFiller.java:71)

It seems to be a problem of my particular environment, and not of the FLIMfit. So I am wondering what could have happened that FLIMfit stopped working and reinstalling it does not help. I am looking for a way to troubleshoot that issue.

**Comment by ilyaradko** [comment]
It seems that Java Development Kit, which I recently installed on my PC, was somehow conflicting with FLIMfit installtion. I reinstalled both JDK and JRE, which solved the problem.

**Comment by seanwarren** [comment]
I'm glad you've resolved this - I'll keep this in mind in case some one else encounters the same problem! Cheers, Sean
