### ISSUE TITLE
clarification regarding errors returned by the fit results

### ISSUE THREAD

**Issue by elizabethnoble0714** [imperial-photonics/FLIMfit#255]
[point probe sample fit result.xlsx](https://github.com/imperial-photonics/FLIMfit/files/418093/point.probe.sample.fit.result.xlsx)

I'm attaching the exported fit results table from single point TCSPC spectral measurements. Trying to figure out how to obtain errors in the fitted model itself.

could you please clarify what's the difference between err_l - tau_1(cell DB1 in the doc attached) and err_u - tau_1 (DM1 in the doc attached) assuming those are errors.

**Comment by seanwarren** [comment]
Hi Elizabeth,

err_u and err_l are respectively the upper and lower 95% confidence intervals for the fit. You can change the percentile in Preferences (Tools menu).

Let me know if you need more information

Cheers
Sean
