### ISSUE TITLE
Segmentation manager problem - incorrectly saved IRF shift map xml (transpose IRF)

### ISSUE THREAD

**Issue by Powerfultool** [imperial-photonics/FLIMfit#266]
This happens after loading a (previously-fitted) folder of FLIMimages, then running the segmentation manager produces this error. Selecting the menu item again will open the manager, allow you to run a segmentation operation on a single image ok, but it falls over when trying 'segment all'
# 

Error using vertcat  
Dimensions of matrices being concatenated are not consistent.                                  

Error in flim_data_series/compute_tr_irf (line 226)                                            

Error in flim_data_series/compute_tr_data (line 263)                                           

Error in flim_data_series/switch_active_dataset (line 78)                                      

Error in flim_data_series/selected_intensity (line 444)                                        

Error in flim_data_series_controller/selected_intensity (line 201)                             

Error in segmentation_controller/update_display (line 36)                                      

Error in segmentation_controller (line 179)                                                    

Error in segmentation_manager>segmentation_manager_OpeningFcn (line 62)                        

Error in gui_mainfcn (line 220)                                                                

Error in segmentation_manager (line 42)                                                        

Error in front_end_menu_controller/menu_segmentation_yuriy_callback (line 1058)                

Error in front_end_menu_controller>@(varargin)obj.menu_segmentation_yuriy_callback(varargin{:})

Error in escaped_callback (line 7)                                                             

Error in front_end_menu_controller>@(x,y)escaped_callback(x,y,fcn) (line 261)

**Comment by imunro** [comment]
Can I ask what FLIMfit  version you are using?

**Comment by Powerfultool** [comment]
4.12.0, on terminalsix

**Comment by imunro** [comment]
Thanks Sunil

**Comment by imunro** [comment]
I've been trying this dataset  smb://ph-nas-04.ph.ic.ac.uk/fogim_datastore/User data/Sunil Kumar/BBSRC platereaders 2015/Raw data/2016-09-30 - Bromodomain plate/Data/Sequenced FLIM acquisition 2016-09-30_18.19.37   and on the mac everything seems fine. Sadly I can't confirm on Windows as t6 doesn't have enough disk space to load this, however I have been able to load & segment a couple of wells without problem. Could I have the wrong data ?

**Comment by imunro** [comment]
Having finally managed (with help from Sunil) to find a way of reproducing this - it turns out to be unrelated to segmentaion but an irf issue!

The problem is in the lines below:
https://github.com/imperial-photonics/FLIMfit/blob/8bd0eef06bfb47139c46b0237615fecf2cbe72cf/FLIMfitFrontEnd/Classes/%40flim_data_series/compute_tr_irf.m#L218-L230

which fail if obj.tr_irf isn't a column vector. 
In the case of this data the irf is a row! It's loaded as a SVirf from a .xml file.

 @seanwarren do you know if both are allowed (in which case it's a simple fix)?  Or is the irf always required to be a column, in which case the problem lies elsewhere - either during loading or generation of the .xml irf.

**Comment by imunro** [comment]
FYI @seanwarren I've checked the .xml and the irf is a row there as well.
Any thoughts on whether to throw an error when on loading  ? Or is this expected?

**Comment by imunro** [comment]
On further investigation I'm beginning to get some idea of what's happening. When a .xml file is created using "create irf shift map" it seems to store data generated by  generate_t0_map see https://github.com/imperial-photonics/FLIMfit/blob/181f35759161f774ee2fc703c47312e6bb37dbca/FLIMfitFrontEnd/Classes/front_end_menu_controller.m#L1124

This data contains a field "t_irf" which , I think, is unrelated to the t_irf in data_series, as the latter remains unchanged, and is a row vector.

However if you later load this .xml file using irf->load_irf or irf->load_sv_irf then it is interpreted as an irf and placed in data_series as a row vector -  giving rise to the current issue.

I have yet to establish whether this is a bug or that simply this is not how to use the resulting .xml and http://docs.flimfit.org/advanced.html  isn't clear on this.

**Comment by imunro** [comment]
Looking at https://github.com/imperial-photonics/FLIMfit/blob/181f35759161f774ee2fc703c47312e6bb37dbca/FLIMfitFrontEnd/Classes/%40flim_data_series/generate_t0_map.m#L171-L176
it looks as if my comment above was wrong and the t_irf in the .xml file is typically data_series.t_irf.  In which case the question  now becomes - did @Powerfultool have an irf loaded when the ,xml was created?

**Comment by imunro** [comment]
So it looks as if the problem is the irf saved with the shift_map when no IRF is loaded. (See above commit.) The obvious work-around , in the meantime, is to explicitly set an irf before creating the shift map.  @powerfultool do you think you could try that ,when you have time, and see if you still have segmentation issues?

**Comment by imunro** [comment]
I've just spotted a potential issue with, at least my copy of @Powerfultool 's data. There seems to be one file that Bio-Formats recognises as a .tiff not an ome-tiff.  FLIMfit is not currently handling this situation well.
