### ISSUE TITLE
Look at replacing mem-mapping with tall arrays.

### ISSUE THREAD

**Issue by imunro** [imperial-photonics/FLIMfit#267]
See 
https://uk.mathworks.com/help/matlab/examples/analyze-big-data-in-matlab-using-tall-arrays.html

**Comment by seanwarren** [comment]
These look interesting but I'm not sure they will work for us - the nice thing about memory mapped files is both the front and back end can access at the same time without any transfer overhead. Also we have very predictable memory access so I think it's probably more efficient to handle the mapping ourselves

**Comment by imunro** [comment]
Good point. I'd forgotten that. Interesting feature though.
