### ISSUE TITLE
Possible problem when using Global Variable - "Row"

### ISSUE THREAD

**Issue by imunro** [imperial-photonics/FLIMfit#279]
Warning: Error occurred while executing callback:
Matrix dimensions must agree.
Error in flim_fit_controller/filter_table_updated (line 95)
Error in flim_fit_controller/update_filter_table (line 391)
Error in flim_fit_controller/fit_complete (line 56)
Error in flim_fit_controller>@(varargin)obj.fit_complete(varargin{:}) (line 141)
Error in flim_dll_interface/update_progress (line 46)
Error in flim_dll_interface/fit>@(varargin)obj.update_progress(varargin{:}) (line 197)
Error in timer/timercb (line 30)
Error in timercb (line 13)
Error in flim_fit_ui (line 241)
Error in FLIMfit (line 39)
> In flim_dll_interface/update_progress (line 46)
  In flim_dll_interface/fit>@(varargin)obj.update_progress(varargin{:}) (line 197)
  In timer/timercb (line 30)
  In timercb (line 13)
  In flim_fit_ui (line 241)
  In FLIMfit (line 39)

**Comment by imunro** [comment]
@Powerfultool do you need this functionality urgently ?

**Comment by Powerfultool** [comment]
It’s not super urgent – would be nice to have, basically (assuming it’s doing what I think it is)

**Comment by imunro** [comment]
The docs say "Global Variable combo-box to confine the scope of the global fit to a particular multi-well plate metadata parameter (e.g. ‘Row’ or ‘Column’). If a parameter is selected all images with the same parameter value will be globally analysed together."  If that's what you need ?

**Comment by Powerfultool** [comment]
That’s what I was relying on – basically whether it’s possible to get sensible results for an experiment where there’s a variety of different things going on – probably useful for separating out some control stuff we’re doing at the moment, although I guess it’s possible to do that by changing what’s fitted in the data manager, if a bit time-consuming on occasion

**Comment by imunro** [comment]
The problem manifests in these lines 

https://github.com/imperial-photonics/FLIMfit/blob/181f35759161f774ee2fc703c47312e6bb37dbca/FLIMfitFrontEnd/Classes/%40flim_fit_controller/filter_table_updated.m#L91-L95

where if I fit a 2x3 plate globally fit_result.image_size has 6 entries & fit_result.n_results ==6 so all is well.

If Global_variable is et to 'row' then there are only 3 entries in fit_result.image_size !!

**Comment by Powerfultool** [comment]
Well, I guess if there’s only 3 rows… Duplicate the entries? If they’re a global, after all…

**Comment by imunro** [comment]
@seanwarren If you need me to tackle this one just let me know,

**Comment by seanwarren** [comment]
So I've looked into this now. Quite a while ago I substantially modified the way FLIMfit talks to the backend, to reduce the memory use among other things. This broke the global variable feature (which essentially makes multiple calls to the backend). I should be able to restore this feature but it will take a little while. 

I've made a small fix so far (PR287) which correctly retrieves the images stats.  At the moment you won't be able to get the images themselves though.

I'll keep you posted

**Comment by seanwarren** [comment]
OK so that wasn't quite as bad as I thought. There is a new version to test here:

http://ci.flimfit.org/job/flimfit-merge-win/177/gcsObjects/

You should get the images this time too
If you have a chance could you have a look and let me know how you get on?

**Comment by Powerfultool** [comment]
Looks like it’s behaving on the first test dataset I tried it on, which is good news! Images are accessible, and from a glance, the values seem believable

**Comment by seanwarren** [comment]
Resolved by PR287
