### ISSUE TITLE
Intermittent "Painter's mode" warnings under Windows (on terminalfive)

### ISSUE THREAD

**Issue by imunro** [imperial-photonics/FLIMfit#84]
While testing Ff 4.7.0 Sometimes get:
"Warning: RGB color data not yet supported in painter's mode. 
No other symptoms &  so far I have failed to reproduce reliably.

**Comment by seanwarren** [comment]
@imunro is this still a problem or should we close this?

**Comment by imunro** [comment]
Haven't seen it with the new build yet!
