### ISSUE TITLE
MCR issue on installation

### ISSUE THREAD

**Issue by dougkelly88** [imperial-photonics/FLIMfit#90]
MCR downloads OK during setup and is present on the system, but when attempting to start FLIMfit the following message is displayed: 
![image](https://cloud.githubusercontent.com/assets/3948976/4147820/a5f4f944-341c-11e4-81b0-21abca3900b9.png)

This has occurred on work laptop (WIndows 7 x64, MATLAB 2013a installed) and home laptop (Windows 8.1, MATLAB 2014a installed). First noticed after download/install of FLIMfit 4.7.0. Now no previously installed versions work either (e.g. 4.5.8):
![image](https://cloud.githubusercontent.com/assets/3948976/4147838/ecc2119a-341c-11e4-9477-a51e0d7162f7.png)

**Comment by imunro** [comment]
This seems to have gone with Doug so closing.

**Comment by imunro** [comment]
Re-opened as Romain seems to be having similar issues.
