### ISSUE TITLE
Resizing window panels error

### ISSUE THREAD

**Issue by dougkelly88** [imperial-photonics/FLIMfit#93]
Neither of the two resizable panels function as expected - on button down, they are draggable, but there doesn't seem to be an action linked to button up so the operation isn't completed...

![image](https://cloud.githubusercontent.com/assets/3948976/4371168/a23ab1ee-4313-11e4-80a6-3506254c1f73.png)

![image](https://cloud.githubusercontent.com/assets/3948976/4371180/ceee4ce6-4313-11e4-8381-3cc5260283cb.png)

**Comment by imunro** [comment]
They both appear to work until you load some data then drag zoom seems to interfere.

**Comment by seanwarren** [comment]
Closing as I'm pretty sure this is resolved now
